### ISSUE TITLE
Use the Unpaywall API for filling out the Open Access Green/Gold/etc info

### ISSUE THREAD

**Issue by egonw** [citation-js/isaac-chrome-extension#1]
From the form:

![image](https://user-images.githubusercontent.com/26721/158028128-aeaa88d2-3ac1-495a-8a46-7dd2f7b46bf8.png)

**Comment by larsgw** [comment]
https://unpaywall.org/products/api

**Comment by larsgw** [comment]
https://twitter.com/larswillighagen/status/1502703984452251650

**Comment by egonw** [comment]
Implemented in v1.1.0
